### PR TITLE
Alternative naming for external functions and javadoc

### PR DESCRIPTION
**Pull request by wilmol**
- change english naming for numbered style
  - similar to Netflix RxJava functions
- Update Javadocs too
- Also changed Object array param to varargs

### CODE REVIEW

**Comment by bladecoder** [comment]
Great!

**Comment by wilmol** [comment]
@bladecoder np! Our codebase has 100s of functions so looking forward to new release :)

**Comment by bladecoder** [comment]
Be careful with the use of external functions, they can be executed several times in the same line because Ink sometimes need to evaluate a condition in advance, so they only should be used to read the game state and not to change it.

I'll try to make a release this weekend :)

**Comment by bladecoder** [comment]
I just created the release v0.7.1 with this changes :)

**Pull request merged**
