### PR TITLE
Added a second constructor for performance reason.

### PR DESCRIPTION
**Pull request by joedai**
This should be used when:
    * The story JSON is big
    * New stories need to be created very often

### CODE REVIEW

**Comment by bladecoder** [comment]
Hi,

Just curious, how do you use this constructor when the JSON is big to gain performance and why don't you use the constructor with the json String?

Also, this constructor has almost the same code that the `Story(String jsonString)`. To avoid repeating code, why don't you modify the  `Story(String jsonString)` to call yours after parsing the String.

Best Regars.

**Comment by joedai** [comment]
Hi,
You are absolutely right. I have updated the Story(String jsonString) to call the new one to reuse the code.

The SimpleJson.textToHashMap(jsonString) is very expensive to call, by having the new constructor we will no longer need to parse json strings to hashmaps all the time(we have only one big story JSON to hash), hence the performance gain.

Regards
Joe

**Comment by bladecoder** [comment]
Hi,

I think that you can reuse the Story object instead of creating a new one all the time using your new constructor. Just call the `resetState()` method, it is even quicker than use the constructor with the hasmap. What do you think?

**Comment by joedai** [comment]
Hi,

The app we are running is a chatbot, which means there will be a lot of conversations simultaneously. Reusing the story object means we need to synchronise the calls to the Story object as Story itself is not stateless. We do have implemented a pool-like mechanism to reduce the creation of Stroy objects. But it would be nice to make the Story constructor less expensive. Cheers.

**Comment by bladecoder** [comment]
Hi,

I think that you can use the constructor `public Story(Container contentContainer, List<ListDefinition> lists)` that is less expensive even than your constructor:

```
Story s = new Story(alreadyLoadedStory.getMainContainer(), alreadyLoadedStory.getListDefinitions());
s.resetState();
```

I just made all missing Story constructors accesible from outside the package.

Cheers!

**Comment by bladecoder** [comment]
Yes, you need to call the ResetState() to create the `StoryState` object.

**Pull request closed without merging**
